# 🐻‍❄️📦 clippy-action: GitHub action to run Clippy, an up-to-date and modern version of actions-rs/clippy
# Copyright 2023-2024 Noel Towa <cutie@floofy.dev>
# Copyright (c) 2025 StepSecurity
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci
on:
    workflow_dispatch: {}
    push:
        branches:
            - main
        paths-ignore:
            - '.github/**'
            - '.eslintignore'
            - '.gitignore'
            - 'dist/**'
            - '**.md'
            - 'LICENSE'

    pull_request:
        types: [opened, synchronize]
        paths-ignore:
            - '.eslintignore'
            - '.gitignore'
            - '**.md'
            - 'LICENSE'

jobs:
    linting:
        name: Lint & Testing
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Setup Bun
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
  
            - name: Install dependencies
              run: npm ci

            - name: Lint project
              run: npm run lint

            - name: Format project
              run: npm run fmt

            - name: Run tests
              run: npm test
